// Blog sitemap data for inclusion in main sitemap.xml
export const blogUrls = [
  { url: "/blog", priority: 0.8, changefreq: "weekly" },
  { url: "/blog/performance-recruiting-was-ist-das", priority: 0.9, changefreq: "monthly" },
  { url: "/blog/performance-recruiting-kosten", priority: 0.9, changefreq: "monthly" },
  { url: "/blog/social-media-recruiting-leitfaden", priority: 0.8, changefreq: "monthly" },
  { url: "/blog/bewerberfunnel-erstellen", priority: 0.7, changefreq: "monthly" },
  { url: "/blog/recruiting-roi-berechnen", priority: 0.7, changefreq: "monthly" },
  { url: "/blog/mitarbeiter-finden-handwerk", priority: 0.9, changefreq: "monthly" },
  { url: "/blog/pflegekraefte-finden", priority: 0.8, changefreq: "monthly" },
  { url: "/blog/mitarbeiter-finden-gastronomie", priority: 0.8, changefreq: "monthly" },
  { url: "/blog/mitarbeiter-finden-logistik", priority: 0.8, changefreq: "monthly" },
  { url: "/blog/employer-branding-handwerk", priority: 0.8, changefreq: "monthly" },
  { url: "/blog/employer-branding-video", priority: 0.7, changefreq: "monthly" },
  { url: "/blog/tiktok-recruiting", priority: 0.7, changefreq: "monthly" },
  { url: "/blog/linkedin-recruiting-strategie", priority: 0.7, changefreq: "monthly" },
  { url: "/blog/neukundengewinnung-strategien", priority: 0.9, changefreq: "monthly" },
  { url: "/blog/meta-ads-leadgenerierung", priority: 0.8, changefreq: "monthly" },
  { url: "/blog/b2b-leadgenerierung", priority: 0.7, changefreq: "monthly" },
  { url: "/blog/digitale-neukundengewinnung-handwerk", priority: 0.8, changefreq: "monthly" },
  { url: "/blog/facebook-werbung-kosten", priority: 0.7, changefreq: "monthly" },
  { url: "/blog/landing-page-optimierung", priority: 0.7, changefreq: "monthly" },
  { url: "/blog/conversion-rate-optimierung", priority: 0.7, changefreq: "monthly" },
  { url: "/blog/social-media-marketing-kmu", priority: 0.7, changefreq: "monthly" },
  { url: "/blog/was-kostet-social-media-marketing", priority: 0.7, changefreq: "monthly" },
  { url: "/blog/content-marketing-strategie", priority: 0.7, changefreq: "monthly" },
  { url: "/blog/website-erstellen-lassen-kosten", priority: 0.7, changefreq: "monthly" },
  { url: "/blog/shopify-shop-erstellen", priority: 0.7, changefreq: "monthly" },
  { url: "/blog/seo-fuer-handwerker", priority: 0.8, changefreq: "monthly" },
  { url: "/blog/google-ads-handwerk", priority: 0.7, changefreq: "monthly" },
  { url: "/blog/fachkraeftemangel-deutschland", priority: 0.8, changefreq: "monthly" },
  { url: "/blog/personalgewinnung-2026", priority: 0.7, changefreq: "monthly" },
  { url: "/blog/recruiting-agentur-vergleich", priority: 0.7, changefreq: "monthly" },
];
